export const autoCompleteData = {
	data: {

	}

}

export const complexSearchData = {
	data: {
		number: 12,
		offset: 0,
		totalResults: 1322,
		results: [
			{
				aggregateLikes: 32767,
				cuisines: [],
				dishTypes:['lunch', 'main course', 'main dish', 'dinner'],
				id: 7765051,
				image : "https://spoonacular.com/recipeImages/776505-312x231.jpg",
				readyInMinutes: 28,
				servings: 6,
				summary: "Sausage & Pepperoni Stromboli might be just the main course you are searching for. For <b>$2.58 per serving</b>, this recipe <b>covers 19%</b> of your daily requirements of vitamins and minerals. One serving contains <b>689 calories</b>, <b>33g of protein</b>, and <b>45g of fat</b>. This recipe is liked by 64426 foodies and cooks. A mixture of egg, mozzarella cheese, parmesan cheese, and a handful of other ingredients are all it takes to make this recipe so yummy. To use up the pizza dough you could follow this main course with the <a href=\"https://spoonacular.com/recipes/grilled-dessert-pizza-203680\">Grilled Dessert Pizza</a> as a dessert. All things considered, we decided this recipe <b>deserves a spoonacular score of 70%</b>. This score is good. Try <a href=\"https://spoonacular.com/recipes/pepperoni-sausage-stromboli-570172\">Pepperoni & Sausage Stromboli</a>, <a href=\"https://spoonacular.com/recipes/pepperoni-stromboli-176095\">Pepperoni Stromboli</a>, and <a href=\"https://spoonacular.com/recipes/pepperoni-stromboli-444704\">Pepperoni Stromboli</a> for similar recipes.",
				title: "Sausage & Pepperoni Stromboli",
				vegetarian: false,
				veryHealthy: false,
				veryPopular: true,
			},
			{
				aggregateLikes: 327672,
				cuisines: [],
				dishTypes: ['dessert'],
				id: 715449,
				image: "https://spoonacular.com/recipeImages/715449-312x231.jpg",
				readyInMinutes: 40,
				servings: 48,
				summary: "How to Make OREO Turkeys for Thanksgiving might be a good recipe to expand your dessert repertoire. This recipe makes 48 servings with <b>122 calories</b>, <b>1g of protein</b>, and <b>7g of fat</b> each. For <b>24 cents per serving</b>, this recipe <b>covers 2%</b> of your daily requirements of vitamins and minerals. It can be enjoyed any time, but it is especially good for <b>Thanksgiving</b>. It is brought to you by Pink When. 59476 people have made this recipe and would make it again. A mixture of candy corn, cream cheese, candy eyes, and a handful of other ingredients are all it takes to make this recipe so tasty. From preparation to the plate, this recipe takes roughly <b>40 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 0%</b>. This score is improvable. Users who liked this recipe also liked <a href=\"https://spoonacular.com/recipes/oreo-turkeys-thanksgiving-snack-138063\">Oreo Turkeys (Thanksgiving Snack)</a>, <a href=\"https://spoonacular.com/recipes/cakespy-thanksgiving-cookie-turkeys-50158\">Cakespy: Thanksgiving Cookie Turkeys</a>, and <a href=\"https://spoonacular.com/recipes/make-ahead-turkey-thanksgiving-gravy-75170\">Make Ahead Turkey (thanksgiving) Gravy</a>.",
				title: "How to Make OREO Turkeys for Thanksgiving",
				vegetarian: false,
				veryHealthy: false, 
				veryPopular: true,
			},
			{
				aggregateLikes: 19636,
				cuisines: [],
				dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
				id: 716410,
				image: "https://spoonacular.com/recipeImages/716410-312x231.jpg",
				readyInMinutes: 45,
				servings: 3,
				summary: "This recipe makes 3 servings with <b>576 calories</b>, <b>21g of protein</b>, and <b>33g of fat</b> each. For <b>$1.55 per serving</b>, this recipe <b>covers 15%</b> of your daily requirements of vitamins and minerals. Head to the store and pick up ricotta, milk, pistachios, and a few other things to make it today. It can be enjoyed any time, but it is especially good for <b>Summer</b>. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. Many people made this recipe, and 19636 would say it hit the spot. It is a good option if you're following a <b>gluten free and vegetarian</b> diet. All things considered, we decided this recipe <b>deserves a spoonacular score of 67%</b>. This score is good. Try <a href=\"https://spoonacular.com/recipes/chocolate-dipped-cannoli-with-pistachios-355861\">Chocolate-Dipped Cannoli with Pistachios</a>, <a href=\"https://spoonacular.com/recipes/soft-cannoli-cookie-sandwiches-with-almond-orange-and-dark-chocolate-683998\">Soft Cannoli Cookie Sandwiches with Almond, Orange, and Dark Chocolate</a>, and <a href=\"https://spoonacular.com/recipes/dark-white-chocolate-chip-oatmeal-cookies-with-pistachios-and-dried-bluberries-608097\">Dark & White Chocolate Chip Oatmeal Cookies with Pistachios and Dried Bluberries</a> for similar recipes.",
				title: "Cannoli Ice Cream w. Pistachios & Dark Chocolate",
				vegetarian: true,
				veryHealthy: false,
				veryPopular: true
			},
			{
				aggregateLikes:11132,
				cuisines:[],
				dishTypes:['side dish'],
				id:716423,
				image:"https://spoonacular.com/recipeImages/716423-312x231.jpg",
				readyInMinutes:45,
				servings:2,
				summary:"Grilled Zucchini with Goat Cheese and Balsamic-Honey Syrup might be just the side dish you are searching for. This recipe serves 2 and costs $2.18 per serving. One serving contains <b>272 calories</b>, <b>8g of protein</b>, and <b>14g of fat</b>. This recipe is liked by 11132 foodies and cooks. It can be enjoyed any time, but it is especially good for <b>The Fourth Of July</b>. From preparation to the plate, this recipe takes about <b>45 minutes</b>. If you have balsamic vinegar, pepper, salt, and a few other ingredients on hand, you can make it. It is a good option if you're following a <b>gluten free and vegetarian</b> diet. All things considered, we decided this recipe <b>deserves a spoonacular score of 77%</b>. This score is solid. Similar recipes include <a href=\"https://spoonacular.com/recipes/grilled-zucchini-with-goat-cheese-and-balsamic-honey-syrup-606467\">Grilled Zucchini with Goat Cheese and Balsamic-Honey Syrup</a>, <a href=\"https://spoonacular.com/recipes/grilled-chicken-salad-with-corn-peaches-blue-cheese-and-balsamic-honey-syrup-809932\">Grilled Chicken Salad with Corn, Peaches, Blue Cheese, and Balsamic-Honey Syrup</a>, and <a href=\"https://spoonacular.com/recipes/grilled-peach-salad-with-toasted-pecans-blue-cheese-and-honey-balsamic-syrup-252021\">Grilled Peach Salad with Toasted Pecans, Blue Cheese and Honey Balsamic Syrup</a>.",
				title:"Grilled Zucchini with Goat Cheese and Balsamic-Honey Syrup",
				vegetarian:true,
				veryHealthy:false,
				veryPopular:true,
			},
			{
				aggregateLikes: 9912,
				cuisines: [],
				dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
				id: 715421,
				image: "https://spoonacular.com/recipeImages/715421-312x231.jpg",
				readyInMinutes: 30,
				servings: 4,
				summary: "Cheesy Chicken Enchilada Quinoa Casserole might be just the main course you are searching for. This gluten free recipe serves 4 and costs <b>$2.62 per serving</b>. One serving contains <b>594 calories</b>, <b>34g of protein</b>, and <b>24g of fat</b>. <b>Autumn</b> will be even more special with this recipe. 9912 people have tried and liked this recipe. From preparation to the plate, this recipe takes about <b>30 minutes</b>. Head to the store and pick up chili powder, cumin, verde enchilada sauce, and a few other things to make it today. To use up the avocado you could follow this main course with the <a href=\"https://spoonacular.com/recipes/chocolate-avocado-mousse-quick-dark-chocolate-avocado-mousse-486646\">chocolate avocado mousse | quick dark chocolate avocado mousse</a> as a dessert. This recipe is typical of Mexican cuisine. All things considered, we decided this recipe <b>deserves a spoonacular score of 98%</b>. This score is excellent. Try <a href=\"https://spoonacular.com/recipes/cheesy-chicken-enchilada-casserole-163123\">Cheesy Chicken Enchilada Casserole</a>, <a href=\"https://spoonacular.com/recipes/quinoa-chicken-enchilada-casserole-622079\">Quinoa Chicken Enchilada Casserole</a>, and <a href=\"https://spoonacular.com/recipes/the-heartbreak-of-success-and-a-healthy-easy-and-cheesy-chicken-and-brown-rice-enchilada-casserole-575434\">The Heartbreak of Success, and A Healthy, Easy, and Cheesy Chicken and Brown Rice Enchilada Casserole</a> for similar recipes.",
				title: "Cheesy Chicken Enchilada Quinoa Casserole",
				vegetarian: false,
				veryHealthy: false,
				veryPopular: true,
			},
			{
				aggregateLikes:9362,
				cuisines:[],
				dishTypes:['lunch', 'main course', 'main dish', 'dinner'],
				id:715437,
				image:"https://spoonacular.com/recipeImages/715437-312x231.jpg",
				readyInMinutes:65,
				servings:6,
				summary:"Homemade King Ranch Chicken Casserole might be just the main course you are searching for. One serving contains <b>552 calories</b>, <b>35g of protein</b>, and <b>29g of fat</b>. For <b>$2.49 per serving</b>, this recipe <b>covers 22%</b> of your daily requirements of vitamins and minerals. 9362 people have tried and liked this recipe. If you have mexican cheddar jack cheese, chicken breasts, cream of chicken soup, and a few other ingredients on hand, you can make it. To use up the butter you could follow this main course with the <a href=\"https://spoonacular.com/recipes/cinnamon-butter-cake-60334\">Cinnamon Butter Cake</a> as a dessert. From preparation to the plate, this recipe takes roughly <b>1 hour and 5 minutes</b>. It can be enjoyed any time, but it is especially good for <b>Autumn</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 80%</b>. This score is good. Try <a href=\"https://spoonacular.com/recipes/king-ranch-chicken-casserole-724274\">King Ranch Chicken Casserole</a>, <a href=\"https://spoonacular.com/recipes/king-ranch-chicken-casserole-492773\">King Ranch Chicken Casserole</a>, and <a href=\"https://spoonacular.com/recipes/king-ranch-chicken-casserole-182225\">King Ranch Chicken Casserole</a> for similar recipes.",
				title:"Homemade King Ranch Chicken Casserole",
				vegetarian:false,
				veryHealthy:false,
				veryPopular:true,
			},
			{
				aggregateLikes: 32767,
				cuisines: [],
				dishTypes:['lunch', 'main course', 'main dish', 'dinner'],
				id: 776505,
				image : "https://spoonacular.com/recipeImages/776505-312x231.jpg",
				readyInMinutes: 28,
				servings: 6,
				summary: "Sausage & Pepperoni Stromboli might be just the main course you are searching for. For <b>$2.58 per serving</b>, this recipe <b>covers 19%</b> of your daily requirements of vitamins and minerals. One serving contains <b>689 calories</b>, <b>33g of protein</b>, and <b>45g of fat</b>. This recipe is liked by 64426 foodies and cooks. A mixture of egg, mozzarella cheese, parmesan cheese, and a handful of other ingredients are all it takes to make this recipe so yummy. To use up the pizza dough you could follow this main course with the <a href=\"https://spoonacular.com/recipes/grilled-dessert-pizza-203680\">Grilled Dessert Pizza</a> as a dessert. All things considered, we decided this recipe <b>deserves a spoonacular score of 70%</b>. This score is good. Try <a href=\"https://spoonacular.com/recipes/pepperoni-sausage-stromboli-570172\">Pepperoni & Sausage Stromboli</a>, <a href=\"https://spoonacular.com/recipes/pepperoni-stromboli-176095\">Pepperoni Stromboli</a>, and <a href=\"https://spoonacular.com/recipes/pepperoni-stromboli-444704\">Pepperoni Stromboli</a> for similar recipes.",
				title: "Sausage & Pepperoni Stromboli",
				vegetarian: false,
				veryHealthy: false,
				veryPopular: true,
			},
			{
				aggregateLikes: 32767,
				cuisines: [],
				dishTypes: ['dessert'],
				id: 715449,
				image: "https://spoonacular.com/recipeImages/715449-312x231.jpg",
				readyInMinutes: 40,
				servings: 48,
				summary: "How to Make OREO Turkeys for Thanksgiving might be a good recipe to expand your dessert repertoire. This recipe makes 48 servings with <b>122 calories</b>, <b>1g of protein</b>, and <b>7g of fat</b> each. For <b>24 cents per serving</b>, this recipe <b>covers 2%</b> of your daily requirements of vitamins and minerals. It can be enjoyed any time, but it is especially good for <b>Thanksgiving</b>. It is brought to you by Pink When. 59476 people have made this recipe and would make it again. A mixture of candy corn, cream cheese, candy eyes, and a handful of other ingredients are all it takes to make this recipe so tasty. From preparation to the plate, this recipe takes roughly <b>40 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 0%</b>. This score is improvable. Users who liked this recipe also liked <a href=\"https://spoonacular.com/recipes/oreo-turkeys-thanksgiving-snack-138063\">Oreo Turkeys (Thanksgiving Snack)</a>, <a href=\"https://spoonacular.com/recipes/cakespy-thanksgiving-cookie-turkeys-50158\">Cakespy: Thanksgiving Cookie Turkeys</a>, and <a href=\"https://spoonacular.com/recipes/make-ahead-turkey-thanksgiving-gravy-75170\">Make Ahead Turkey (thanksgiving) Gravy</a>.",
				title: "How to Make OREO Turkeys for Thanksgiving",
				vegetarian: false,
				veryHealthy: false, 
				veryPopular: true,
			},
			{
				aggregateLikes: 19636,
				cuisines: [],
				dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
				id: 716410,
				image: "https://spoonacular.com/recipeImages/716410-312x231.jpg",
				readyInMinutes: 45,
				servings: 3,
				summary: "This recipe makes 3 servings with <b>576 calories</b>, <b>21g of protein</b>, and <b>33g of fat</b> each. For <b>$1.55 per serving</b>, this recipe <b>covers 15%</b> of your daily requirements of vitamins and minerals. Head to the store and pick up ricotta, milk, pistachios, and a few other things to make it today. It can be enjoyed any time, but it is especially good for <b>Summer</b>. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. Many people made this recipe, and 19636 would say it hit the spot. It is a good option if you're following a <b>gluten free and vegetarian</b> diet. All things considered, we decided this recipe <b>deserves a spoonacular score of 67%</b>. This score is good. Try <a href=\"https://spoonacular.com/recipes/chocolate-dipped-cannoli-with-pistachios-355861\">Chocolate-Dipped Cannoli with Pistachios</a>, <a href=\"https://spoonacular.com/recipes/soft-cannoli-cookie-sandwiches-with-almond-orange-and-dark-chocolate-683998\">Soft Cannoli Cookie Sandwiches with Almond, Orange, and Dark Chocolate</a>, and <a href=\"https://spoonacular.com/recipes/dark-white-chocolate-chip-oatmeal-cookies-with-pistachios-and-dried-bluberries-608097\">Dark & White Chocolate Chip Oatmeal Cookies with Pistachios and Dried Bluberries</a> for similar recipes.",
				title: "Cannoli Ice Cream w. Pistachios & Dark Chocolate",
				vegetarian: true,
				veryHealthy: false,
				veryPopular: true
			},
			{
				aggregateLikes:11132,
				cuisines:[],
				dishTypes:['side dish'],
				id:716423,
				image:"https://spoonacular.com/recipeImages/716423-312x231.jpg",
				readyInMinutes:45,
				servings:2,
				summary:"Grilled Zucchini with Goat Cheese and Balsamic-Honey Syrup might be just the side dish you are searching for. This recipe serves 2 and costs $2.18 per serving. One serving contains <b>272 calories</b>, <b>8g of protein</b>, and <b>14g of fat</b>. This recipe is liked by 11132 foodies and cooks. It can be enjoyed any time, but it is especially good for <b>The Fourth Of July</b>. From preparation to the plate, this recipe takes about <b>45 minutes</b>. If you have balsamic vinegar, pepper, salt, and a few other ingredients on hand, you can make it. It is a good option if you're following a <b>gluten free and vegetarian</b> diet. All things considered, we decided this recipe <b>deserves a spoonacular score of 77%</b>. This score is solid. Similar recipes include <a href=\"https://spoonacular.com/recipes/grilled-zucchini-with-goat-cheese-and-balsamic-honey-syrup-606467\">Grilled Zucchini with Goat Cheese and Balsamic-Honey Syrup</a>, <a href=\"https://spoonacular.com/recipes/grilled-chicken-salad-with-corn-peaches-blue-cheese-and-balsamic-honey-syrup-809932\">Grilled Chicken Salad with Corn, Peaches, Blue Cheese, and Balsamic-Honey Syrup</a>, and <a href=\"https://spoonacular.com/recipes/grilled-peach-salad-with-toasted-pecans-blue-cheese-and-honey-balsamic-syrup-252021\">Grilled Peach Salad with Toasted Pecans, Blue Cheese and Honey Balsamic Syrup</a>.",
				title:"Grilled Zucchini with Goat Cheese and Balsamic-Honey Syrup",
				vegetarian:true,
				veryHealthy:false,
				veryPopular:true,
			},
			{
				aggregateLikes: 9912,
				cuisines: [],
				dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
				id: 715421,
				image: "https://spoonacular.com/recipeImages/715421-312x231.jpg",
				readyInMinutes: 30,
				servings: 4,
				summary: "Cheesy Chicken Enchilada Quinoa Casserole might be just the main course you are searching for. This gluten free recipe serves 4 and costs <b>$2.62 per serving</b>. One serving contains <b>594 calories</b>, <b>34g of protein</b>, and <b>24g of fat</b>. <b>Autumn</b> will be even more special with this recipe. 9912 people have tried and liked this recipe. From preparation to the plate, this recipe takes about <b>30 minutes</b>. Head to the store and pick up chili powder, cumin, verde enchilada sauce, and a few other things to make it today. To use up the avocado you could follow this main course with the <a href=\"https://spoonacular.com/recipes/chocolate-avocado-mousse-quick-dark-chocolate-avocado-mousse-486646\">chocolate avocado mousse | quick dark chocolate avocado mousse</a> as a dessert. This recipe is typical of Mexican cuisine. All things considered, we decided this recipe <b>deserves a spoonacular score of 98%</b>. This score is excellent. Try <a href=\"https://spoonacular.com/recipes/cheesy-chicken-enchilada-casserole-163123\">Cheesy Chicken Enchilada Casserole</a>, <a href=\"https://spoonacular.com/recipes/quinoa-chicken-enchilada-casserole-622079\">Quinoa Chicken Enchilada Casserole</a>, and <a href=\"https://spoonacular.com/recipes/the-heartbreak-of-success-and-a-healthy-easy-and-cheesy-chicken-and-brown-rice-enchilada-casserole-575434\">The Heartbreak of Success, and A Healthy, Easy, and Cheesy Chicken and Brown Rice Enchilada Casserole</a> for similar recipes.",
				title: "Cheesy Chicken Enchilada Quinoa Casserole",
				vegetarian: false,
				veryHealthy: false,
				veryPopular: true,
			},
			{
				aggregateLikes:9362,
				cuisines:[],
				dishTypes:['lunch', 'main course', 'main dish', 'dinner'],
				id:715437,
				image:"https://spoonacular.com/recipeImages/715437-312x231.jpg",
				readyInMinutes:65,
				servings:6,
				summary:"Homemade King Ranch Chicken Casserole might be just the main course you are searching for. One serving contains <b>552 calories</b>, <b>35g of protein</b>, and <b>29g of fat</b>. For <b>$2.49 per serving</b>, this recipe <b>covers 22%</b> of your daily requirements of vitamins and minerals. 9362 people have tried and liked this recipe. If you have mexican cheddar jack cheese, chicken breasts, cream of chicken soup, and a few other ingredients on hand, you can make it. To use up the butter you could follow this main course with the <a href=\"https://spoonacular.com/recipes/cinnamon-butter-cake-60334\">Cinnamon Butter Cake</a> as a dessert. From preparation to the plate, this recipe takes roughly <b>1 hour and 5 minutes</b>. It can be enjoyed any time, but it is especially good for <b>Autumn</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 80%</b>. This score is good. Try <a href=\"https://spoonacular.com/recipes/king-ranch-chicken-casserole-724274\">King Ranch Chicken Casserole</a>, <a href=\"https://spoonacular.com/recipes/king-ranch-chicken-casserole-492773\">King Ranch Chicken Casserole</a>, and <a href=\"https://spoonacular.com/recipes/king-ranch-chicken-casserole-182225\">King Ranch Chicken Casserole</a> for similar recipes.",
				title:"Homemade King Ranch Chicken Casserole",
				vegetarian:false,
				veryHealthy:false,
				veryPopular:true,
			}
		]
	}
}

