import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import parseCookies, { stringToDate, popupKeywords } from '../helpers'

import FilterSection from '../components/Home/SearchKeywordSection'

import StyledSEarchSection from '../components/SearchBarSection/index'
import StyledMainContent from '../styles/mainContent.styles'
import StyledSubContent from '../styles/subContent.styles'
import StyledHome from '../components/Home/home.styles'
import { Fridge, User } from '../helpers/typesLibrary'
import appAxios from '../constants/axiosBase'


type Props = {
  user: User | null,
  expireFoods: string[],
  keywords: string[]

}

const Home: NextPage<Props> = ({ user, expireFoods, keywords }: Props) => {
  return (
    <StyledHome>
      <Head>
        <title>Home | Cookit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledSEarchSection />
      <StyledMainContent>

      </StyledMainContent>
      <StyledSubContent>
        {expireFoods.length > 0 && 
        <>
          <h3>Expiring Ingredients</h3>
          <FilterSection keywords={expireFoods}/>
        </>
        }
        <h3>What Is In Your Mind</h3>
          <FilterSection keywords={keywords}/>
      </StyledSubContent>
    </StyledHome>
  )
}

export default Home

Home.getInitialProps = async ({ req, res }): Promise<Props> => {
  const cookieData = parseCookies(req)
  const user: User | null = cookieData.user ? JSON.parse(cookieData.user) : null
  const expireFoods: string[] = []
  const keywords = popupKeywords()

  if(user) {
    const fridgeData = await appAxios.post('api/fridge/show', {
      user_id: user.id
    })
    Object.values(fridgeData.data).forEach((value: any) => {
      // TODO: define condition of expire
      if(true) {
        expireFoods.push(value.name)
      }
    })
  }
  
  if(res){
    if (Object.keys(cookieData).length === 0 && cookieData.constructor === Object) {
      res.writeHead(301, { Location: '/'})
      res.end()
    }
  }

  return {
    user,
    expireFoods,
    keywords
  } 
}